"""Turns district priority into concrete project recommendations.

The priority score answers "which district needs attention most". It does not
answer "and what should be built there" - a policymaker holding a budget needs
the second answer, not the first.

A recommendation is derived, not invented: complaints in a district are grouped
by category, and a category with enough weight becomes a proposed intervention
carrying the evidence behind it (how many distinct issues, how severe, how many
people). Nothing here is generated by a model - the LLM only classifies the
individual complaints; the aggregation and ranking are deterministic and
auditable, which is what makes a recommendation defensible to a department.
"""

from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import Complaint, District
from app.services.scoring_service import DistrictScore, compute_scores

# What a cluster of complaints in each category actually implies as a project.
CATEGORY_PROJECTS: dict[str, tuple[str, str]] = {
    "Roads": (
        "Road resurfacing and pothole repair programme",
        "Roads",
    ),
    "Water Supply": (
        "Piped water supply augmentation",
        "Water",
    ),
    "Sanitation": (
        "Solid waste collection and sanitation expansion",
        "Sanitation",
    ),
    "Electricity": (
        "Distribution network upgrade and load balancing",
        "Power",
    ),
    "Public Transport": (
        "Bus route and service frequency expansion",
        "Transport",
    ),
    "Healthcare": (
        "Primary health centre staffing and equipment",
        "Health",
    ),
    "Drainage": (
        "Storm water drainage and sewerage works",
        "Drainage",
    ),
    "Street Lighting": (
        "Street lighting installation and repair",
        "Lighting",
    ),
    "Other": (
        "Field assessment to characterise reported issues",
        "Assessment",
    ),
}

# A recommendation is weighted differently from a district score. Severity
# dominates because it decides what a department should build FIRST, while
# district need is a context multiplier rather than the main driver.
WEIGHTS = {"severity": 0.45, "volume": 0.30, "district_need": 0.25}

# Below this, a category is noise rather than a pattern worth funding.
MIN_ISSUES = 2


@dataclass
class Recommendation:
    district: District
    district_rank: int
    district_score: float
    category: str
    project: str
    sector: str
    issue_count: int
    repeat_reports: int
    average_severity: float
    people_affected: int
    score: float = 0.0

    @property
    def rationale(self) -> str:
        """One sentence a policymaker can put in a file note."""
        return (
            f"{self.issue_count} distinct {self.category.lower()} complaints in "
            f"{self.district.name} at average severity "
            f"{self.average_severity:.1f}/5"
            + (
                f", corroborated by {self.repeat_reports} repeat reports"
                if self.repeat_reports
                else ""
            )
            + f", affecting an estimated {self.people_affected:,} people."
        )


def _category_rows(db: Session) -> dict[tuple[int, str], dict]:
    """Aggregate canonical complaints per district and category."""
    stmt = select(Complaint).where(
        Complaint.duplicate_of.is_(None),
        Complaint.category.is_not(None),
        Complaint.district_id.is_not(None),
    )
    grouped: dict[tuple[int, str], dict] = {}
    for complaint in db.execute(stmt).scalars():
        key = (complaint.district_id, complaint.category)
        row = grouped.setdefault(
            key, {"count": 0, "severity_sum": 0, "people": 0, "repeats": 0}
        )
        row["count"] += 1
        row["severity_sum"] += complaint.severity or 0
        row["people"] += complaint.population_affected or 0
        row["repeats"] += complaint.duplicate_count or 0
    return grouped


def compute_recommendations(db: Session) -> list[Recommendation]:
    """Rank proposed projects across every district, highest need first."""
    scores: dict[int, DistrictScore] = {
        s.district.id: s for s in compute_scores(db)
    }
    grouped = _category_rows(db)
    if not grouped:
        return []

    max_count = max(row["count"] for row in grouped.values()) or 1

    recommendations: list[Recommendation] = []
    for (district_id, category), row in grouped.items():
        if row["count"] < MIN_ISSUES:
            continue
        score = scores.get(district_id)
        if score is None:
            continue

        project, sector = CATEGORY_PROJECTS.get(
            category, CATEGORY_PROJECTS["Other"]
        )
        average_severity = row["severity_sum"] / row["count"]

        recommendation = Recommendation(
            district=score.district,
            district_rank=score.rank,
            district_score=score.priority_score,
            category=category,
            project=project,
            sector=sector,
            issue_count=row["count"],
            repeat_reports=row["repeats"],
            average_severity=round(average_severity, 2),
            people_affected=row["people"],
        )
        recommendation.score = round(
            100
            * (
                WEIGHTS["severity"] * (average_severity / 5)
                + WEIGHTS["volume"] * (row["count"] / max_count)
                + WEIGHTS["district_need"] * (score.priority_score / 100)
            ),
            1,
        )
        recommendations.append(recommendation)

    recommendations.sort(key=lambda r: r.score, reverse=True)
    return recommendations


def recommendations_for(db: Session, district_id: int) -> list[Recommendation]:
    """Proposed projects for one district, most urgent first."""
    return [r for r in compute_recommendations(db) if r.district.id == district_id]
